### ISSUE TITLE
"Can't set errors after they are sent" error

### ISSUE THREAD

**Issue by takkaria** [takkaria/echojs#97]
Keep on getting echojs falling over due to this error:

```
00:49:20 web.2 |  http.js:690
00:49:20 web.2 |  throw new Error('Can\'t set headers after they are sent.'…
00:49:20 web.2 |  ^
00:49:29 web.2 |  Error: Can't set headers after they are sent.
00:49:29 web.2 |  at ServerResponse.OutgoingMessage.setHeader (http.js:690:…
00:49:29 web.2 |  at ServerResponse.header (/var/www/echomanchester.net/ech…
00:49:29 web.2 |  at ServerResponse.send (/var/www/echomanchester.net/echoj…
00:49:29 web.2 |  at fn (/var/www/echomanchester.net/echojs/node_modules/ex…
00:49:29 web.2 |  at /var/www/echomanchester.net/echojs/node_modules/swig/l…
00:49:29 web.2 |  at /var/www/echomanchester.net/echojs/node_modules/swig/l…
00:49:29 web.2 |  at fs.js:272:14
00:49:29 web.2 |  at Object.oncomplete (fs.js:108:15)
```

Some digging suggests there may be times when we call response.end() twice.  This might be a pain to track down.  Some info: https://stackoverflow.com/questions/26307920/res-json-cant-set-headers-after-they-are-sent

**Comment by takkaria** [comment]
So this was quite a complex bug with two parts.

11b08909ea2ba2a4d61cb351d6e4e39711c4f0bd - One was that the error handlers in app.js were trying to set the status code after the content had started being sent.  I fixed that by defaulting to the Express built-in error handler when headers had been sent already, as suggested in the Express docs.

6f4a2d3dcb0ccfcc3dd26f4f9b6caa7f1bdd8f25 - However the underlying cause of the error was SQLite sometimes erroring with SQLITE_BUSY when the two requests came in at the same time and the session code tried to create two new sessions.  I hunted for how to fix this and couldn't find anything so switched to using a file-based store instead.
